includes:
- ./base.yml
- ../visual_encoder/pvt.yml

task_attributes:
  univl_task:
    dataset_attributes:
      video_text_retrieval:
        data_root_dir: /YourPath/didemo/

        annotations:
          train: didemo_retrieval/train.jsonl
          val: didemo_retrieval/val.jsonl
          test: didemo_retrieval/test.jsonl

        train_ensemble_n_clips: 16 # 8 for full test
        test_ensembel_n_clips: 16 # 16 for full test

        # support lmdb database for faster reading, convert video to lmdb:
        # prj/univl/scripts/lmdb_conversion.py
        videos:
          train: didemo_videos.lmdb
          val: didemo_videos.lmdb
          test: didemo_videos.lmdb

        caption_processor:
          type: masked_bert_tokenizer
          params:
            max_seq_length: 30 # max_length for each text field


model_attributes:
  univl:
    image_encoder:
      type: DetrBatchPVTImageEncoder
      params:
        gradient_checkpointing: [true, true, true, true]


optimizer_attributes:
  type: AdamW
  params:
    lr: 1e-5
    betas: [0.9, 0.98]
    weight_decay: 1e-4

training_parameters:
  batch_size: 32
  test_batch_size: 32

  load_pretrained: True
  pretrained_mapping:
    module.model.model.module: module.model.module
