includes:
- ./base.yml
- ../visual_encoder/pvt.yml

task_attributes:
  univl_task:
    dataset_attributes:
      video_text_retrieval:
        processors:
          caption_processor:
            type: masked_bert_tokenizer
            params:
              tokenizer_config:
                type: bert-base-chinese

        data_root_dir: ../tests/data/video/

        annotations:
          train: VATEX_CN.jsonl
          val: VATEX_CN.jsonl
          test: VATEX_CN.jsonl

        train_ensemble_n_clips: 3 # 8 for full test
        test_ensembel_n_clips: 2 # 16 for full test

        # support lmdb database for faster reading, convert video to lmdb:
        # prj/univl/scripts/lmdb_conversion.py
        videos:
          train: .
          val: data/mp4.lmdb
          test: data/mp4.lmdb

model_attributes:
  univl:
    image_encoder:
      type: DetrBatchPVTImageEncoder
      params:
        gradient_checkpointing: [true, true, true, true]

    text_encoder:
      params:
        bert_model_name: bert-base-chinese
        vocab_size: 21128

    cross_encoder:
      params:
        bert_model_name: bert-base-chinese
        vocab_size: 21128


optimizer_attributes:
  type: AdamW
  params:
    lr: 1e-5
    betas: [0.9, 0.98]
    weight_decay: 1e-4

training_parameters:
  batch_size: 2
  test_batch_size: 2
  num_workers: 0

  load_pretrained: True
  pretrained_mapping:
    module.model.model.module: module.model.module