includes:
- ./base.yml
- ../visual_encoder/pvt.yml

task_attributes:
  univl_task:
    dataset_attributes:
      video_text_retrieval:
        data_root_dir: /YourPath/msvd/

        annotations:
          train: msvd_retrieval/MSVD_train.jsonl
          val: msvd_retrieval/MSVD_test.jsonl
          test: msvd_retrieval/MSVD_test.jsonl

        train_ensemble_n_clips: 16 # 8 for full test
        test_ensembel_n_clips: 16 # 16 for full test
        num_frm: 1

        # support lmdb database for faster reading, convert video to lmdb:
        # prj/univl/scripts/lmdb_conversion.py
        videos:
          train: YouTubeClips
          val: YouTubeClips
          test: YouTubeClips

model_attributes:
  univl:
    image_encoder:
      type: DetrBatchPVTImageEncoder
      params:
        gradient_checkpointing: [true, true, true, true]


optimizer_attributes:
  type: AdamW
  params:
    lr: 1e-6
    betas: [0.9, 0.98]
    weight_decay: 1e-4

training_parameters:
  batch_size: 128
  test_batch_size: 32
  max_iterations: 16000
  snapshot_interval: 2000
  lr_steps: # 12 epoch
    - 8000

  load_pretrained: True
  pretrained_mapping:
    module.model.model.module: module.model.module
    module.model.model: module.model # 加载预训练similarity_dense
