includes:
- ./base.yml
- ../visual_encoder/resnet.yml

task_attributes:
  univl_task:
    dataset_attributes:
      video_text_pretrain:
        data_root_dir: /YourPath/public

        annotations:
          train:
            - annotations/coco_train2017_pretrain_format_with_subfix.jsonl
            - annotations/image_val_left.jsonl
            - annotations/region_desc_pretrain_format_with_subfix.jsonl
            - annotations/cc_train.jsonl
          val: annotations/image_val.jsonl
          test: annotations/image_val.jsonl

        train_ensemble_n_clips: 1 # image consider as 1 clip with num_frm=1
        test_ensembel_n_clips: 1
        num_frm: 1

        images:
          train: .
          val: .
          test: .

        processors:
          caption_processor: &caption_processor
            type: masked_bert_tokenizer
            params:
              max_seq_length: 30 # max_length for each text field
              mask_probability: 0.15

model_attributes:
  univl:
    img_embeddings:
      params:
        pixel_random_sampling_size: 100

# coco image + visual genome: 15.1 k images, 5.6M training image-text pairs
training_parameters:
  lr_scheduler: true
  lr_ratio: 0.1
  lr_epochs: []
  lr_steps: # 12 epoch
    - 150000
  use_warmup: true
  warmup_factor: 0.1
  warmup_iterations: 2000
  max_iterations: 400000
  batch_size: 128