includes:
- ./EN_coco_vg_cc_videoswin.yml

task_attributes:
  univl_task:
    dataset_attributes:
      video_text_pretrain:
        data_root_dir: ../tests/data

        annotations:
          train:
           - video/univl_img.jsonl
          val: video/univl_img.jsonl
          test: video/univl_img.jsonl

        images:
          train: image
          val: image
          test: image

training_parameters:
  batch_size: 2
  log_interval: 2
  num_workers: 0