includes:
- ./base.yml
- ../visual_encoder/pvt.yml

task_attributes:
  univl_task:
    dataset_attributes:
      video_text_retrieval:
        data_root_dir: /YourPath/msr_vtt/

        annotations:
          train: msrvtt_retrieval/train.jsonl
          val: msrvtt_retrieval/val.jsonl
          test: msrvtt_retrieval/test.jsonl

        train_ensemble_n_clips: 16 # 8 for full test
        test_ensembel_n_clips: 16 # 16 for full test
        num_frm: 1

        # support lmdb database for faster reading, convert video to lmdb:
        # prj/univl/scripts/lmdb_conversion.py
        videos:
          train: msrvtt_videos.lmdb
          val: msrvtt_videos.lmdb
          test: msrvtt_videos.lmdb

model_attributes:
  univl:
    image_encoder:
      type: DetrBatchPVTImageEncoder
      params:
        gradient_checkpointing: [true, true, true, true]


optimizer_attributes:
  type: AdamW
  params:
    lr: 1e-5
    betas: [0.9, 0.98]
    weight_decay: 1e-4

training_parameters:
  batch_size: 32
  test_batch_size: 32

  load_pretrained: True
  pretrained_mapping:
    module.model.model.module: module.model.module
    module.model.model: module.model # 加载预训练similarity_dense
